import {
  IconBrandReact,
  IconBrandAngular,
  IconBrandJavascript,
  IconBrandTypescript,
  IconBrandNextjs,
  IconBrandHtml5,
  IconBrandCss3,
  IconBrandCSharp,
  IconBrandAuth0,
  IconBrandAws,
  IconBrandAzure,
  IconBrandBootstrap,
  IconBrandCloudflare,
  IconBrandCypress,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandFramerMotion,
  IconBrandGit,
  IconBrandGraphql,
  IconBrandMantine,
  IconBrandMongodb,
  IconBrandMysql,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandPnpm,
  IconBrandReactNative,
  IconBrandRedux,
  IconBrandSass,
  IconBrandSocketIo,
  IconBrandStorybook,
  IconBrandTailwind,
  IconBrandYarn,
  IconSql,
  IconBrandVercel,
  IconApi,
} from '@tabler/icons-react'

export const skillsData = [
  { name: 'React', url: 'https://reactjs.org', icon: IconBrandReact },
  { name: 'Angular', url: 'https://angular.io', icon: IconBrandAngular },
  { name: 'Javascript', url: 'https://javascript.com', icon: IconBrandJavascript },
  { name: 'Typescript', url: 'https://typescriptlang.org', icon: IconBrandTypescript },
  { name: 'Next.js', url: 'https://nextjs.org', icon: IconBrandNextjs },
  { name: 'Html5', url: 'https://developer.mozilla.org/es/docs/Web/HTML', icon: IconBrandHtml5 },
  { name: 'Css3', url: 'https://developer.mozilla.org/es/docs/Web/CSS', icon: IconBrandCss3 },
  { name: 'C# & .Net', url: 'https://dotnet.microsoft.com/es-es/languages/csharp', icon: IconBrandCSharp },
  { name: 'Sql - Sql Server and Relational DB', url: 'https://www.w3schools.com/sql/', icon: IconSql },
  { name: 'Graphql', url: 'https://graphql.org/', icon: IconBrandGraphql },
  { name: 'Api - Rest', url: 'https://www.ibm.com/es-es/topics/rest-apis', icon: IconApi },
  { name: 'Bootstrap', url: 'https://getbootstrap.com/', icon: IconBrandBootstrap },
  { name: 'Tailwind', url: 'https://tailwindcss.com/', icon: IconBrandTailwind },
  { name: 'Mantine', url: 'https://mantine.dev/', icon: IconBrandMantine },
  { name: 'Node.js - Express', url: 'https://nodejs.org/en', icon: IconBrandNodejs },
  { name: 'Auth0 & Others', url: 'https://auth0.com/', icon: IconBrandAuth0 },
  { name: 'AWS', url: 'https://aws.amazon.com/', icon: IconBrandAws },
  { name: 'Azure', url: 'https://azure.microsoft.com/', icon: IconBrandAzure },
  { name: 'Vercel', urk: 'https://vercel.com/', icon: IconBrandVercel },
  { name: 'Cloudflare', url: 'https://www.cloudflare.com/', icon: IconBrandCloudflare },
  { name: 'Cypress, Jest & Jasmine', url: 'https://www.cypress.io/', icon: IconBrandCypress },
  { name: 'Docker', url: 'https://www.docker.com/', icon: IconBrandDocker },
  { name: 'Figma', url: 'https://www.figma.com/', icon: IconBrandFigma },
  { name: 'Firebase', url: 'https://firebase.google.com/', icon: IconBrandFirebase },
  { name: 'Framer Motion', url: 'https://www.framer.com/motion/', icon: IconBrandFramerMotion },
  { name: 'GitHub', url: 'https://github.com/', icon: IconBrandGit },
  { name: 'Mongodb & No Relational DBs', url: 'https://www.mongodb.com/', icon: IconBrandMongodb },
  { name: 'Mysql', url: 'https://www.mysql.com/', icon: IconBrandMysql },
  { name: 'Npm', url: 'https://www.npmjs.com/', icon: IconBrandNpm },
  { name: 'Pnpm', url: 'https://pnpm.io/', icon: IconBrandPnpm },
  { name: 'React Native & Ionic', url: 'https://reactnative.dev/', icon: IconBrandReactNative },
  { name: 'Redux, Recoil & Others', url: 'https://redux.js.org/', icon: IconBrandRedux },
  { name: 'Sass, Scss & Less', url: 'https://sass-lang.com/', icon: IconBrandSass },
  { name: 'Socket.io', url: 'https://socket.io/', icon: IconBrandSocketIo },
  { name: 'Storybook', url: 'https://storybook.js.org/', icon: IconBrandStorybook },
  { name: 'Yarn', url: 'https://yarnpkg.com/', icon: IconBrandYarn },
]
