export * from './About'
export * from './FindMe'
export * from './Education'
export * from './Slogan'
export * from './LastestPosts'
export * from './Resume'
export * from './Portfolio'
export * from './Skills'
export * from './Testimonials'
export { default as Home } from './Home'
