export const techList = [
  { key: 'apollo', label: 'Apollo' },
  { key: 'angular', label: 'Angular' },
  { key: 'architecture', label: 'Design & Architecture' },
  { key: 'astro', label: 'Astro' },
  { key: 'auth', label: 'Authentication' },
  { key: 'accesibility', label: 'Accesibility' },
  { key: 'bootstrap', label: 'Bootstrap' },
  { key: 'css', label: 'CSS' },
  { key: 'cypress', label: 'Cypress' },
  { key: 'database', label: 'DataBases' },
  { key: 'eslint', label: 'ESLint' },
  { key: 'graphql', label: 'GraphQL' },
  { key: 'html', label: 'Html' },
  { key: 'infra', label: 'Infraestructure' },
  { key: 'javascript', label: 'Javascript' },
  { key: 'jest', label: 'Jest' },
  { key: 'metrics', label: 'Metrics' },
  { key: 'mocha', label: 'Mocha' },
  { key: 'next', label: 'Next' },
  { key: 'package', label: 'Package Managers' },
  { key: 'performance', label: 'Performance' },
  { key: 'prettier', label: 'Prettier' },
  { key: 'puppeteer', label: 'Puppeteer' },
  { key: 'react', label: 'React' },
  { key: 'react-native', label: 'React Native' },
  { key: 'security', label: 'Security' },
  { key: 'seo', label: 'SEO' },
  { key: 'svelte', label: 'Svelte' },
  { key: 'tailwind', label: 'Tailwind' },
  { key: 'testing', label: 'Testing' },
  { key: 'tools', label: 'Tools' },
  { key: 'typescript', label: 'Typescript' },
  { key: 'vite', label: 'Vite' },
  { key: 'vitest', label: 'Vitest' },
  { key: 'vue', label: 'Vue' },
  { key: 'webpack', label: 'Webpack' },
]
